### ISSUE TITLE
docker ipv6 on syno

### ISSUE THREAD

**Issue by Windman1320** [sjtuross/syno-iptables#1]
请问一下我能提pr不，内容是修复群晖docker ipv6，也是内核模块和iptables模块

**Comment by sjtuross** [comment]
可以啊，这个我之前也想过整合在一起，就是文档要按用途再组织一下

另外有这个https://github.com/wangliangliang2/fix_synology_docker_ipv6

**Comment by Windman1320** [comment]
文档上大致差不多，就是使用到的模块不同以及多一个iptables_modules_list。可以按功能分一下，有个小小的建议是根目录的readme放介绍然后需要哪个功能就跳转到对应目录下的readme

**Comment by sjtuross** [comment]
文档上我可以做个表格列出所有模块以及对应的用途，绝大部分内容都是通用的，自编译部分可以分拆出去。目录结构暂时不动，只要把ipv6相关的模块放进去。

另外如果有辅助文件，比如你提到的iptables_modules_list或者什么脚本，可以再单独建一个目录，PR你先提，我看了再说

**Comment by sjtuross** [comment]
是不是有了iptables_modules_list就不用手工加载模块了？这样步骤可以大大简化了，或者把文档中加载模块的部分改成如何制作iptables_modules_list，毕竟不同系统不同用途这个文件会不一样，还是以教为主

**Comment by Windman1320** [comment]
> 

不确定，但是iptables_modules_list可能要重启才生效，没有insmod来得直接。有一个问题就是，iptables_modules_list从名字来看是针对iptable相关的，如果是其他功能改这个文件理论上不会有用，不具备通用性。你那边的透明代理理论上来讲也能使用iptables_modules_list，毕竟都是针对iptables的修改。pr我晚些时候提交上去。

**Comment by Windman1320** [comment]
> 是不是有了iptables_modules_list就不用手工加载模块了？这样步骤可以大大简化了，或者把文档中加载模块的部分改成如何制作iptables_modules_list，毕竟不同系统不同用途这个文件会不一样，还是以教为主

外如何修改iptables_modules_list我可以顺便提上去，或许你可以在我提pr之后再测试

**Comment by sjtuross** [comment]
好的，有空我来测试一下iptables_modules_list

**Comment by Windman1320** [comment]
> 好的，有空我来测试一下iptables_modules_list

iptables_modules_list的方式似乎不具备通用性，如果透明代理也想通过此方式加载模块，那么应放置在何处，目前我并不知道这一点。
