### ISSUE TITLE
大佬好，请问能来一份3615xs 3.10.102 DSM 6.1.7-15284 的嘛，比心

### ISSUE THREAD

**Issue by zbjdonald** [sjtuross/syno-iptables#14]

**Comment by zbjdonald** [comment]
iptables 是这个版本目前 v1.6.0

**Comment by sjtuross** [comment]
https://github.com/sjtuross/syno-iptables/tree/master/bromolow/kernel-3.10.102

编译了一份，你试试吧，我没这老系统测试

**Comment by zbjdonald** [comment]
谢谢我测试一下
