### ISSUE TITLE
感谢解决了我的大问题。提个小建议，能否加个安装操作脚本？

### ISSUE THREAD

**Issue by merlinus2019** [sjtuross/syno-iptables#15]
我下载了module以后，按说明操作后，我的群晖终于完整了，可以科学了。
太感谢了！
但是linux对很多新手还是比较难，如果可以加个安装脚本，这样能解决很多人的问题和推广

**Comment by mastomato** [comment]
为啥我还是科学不了

**Comment by mastomato** [comment]
只有openclash能用
