### ISSUE TITLE
想自编译，容器中没有对应版本怎么处理

### ISSUE THREAD

**Issue by redjumper** [sjtuross/syno-iptables#26]
broadwell-6.1.7, linux kernel是3.10.102
运行了容器，发现/spksrc/kernel/和/spksrc/toolchain/下只有syno-broadwell-6.1，没有syno-broadwell-6.1.7。请问是直接使用syno-broadwell-6.1来编译吗

**Comment by sjtuross** [comment]
我觉得用6.1应该可以的。只有内核升级了或者内核编译选项有变化，群晖才会发布新的kernel和toolchain

**Comment by redjumper** [comment]
多谢解释
