### ISSUE TITLE
7.2版本之前的ko不可用

### ISSUE THREAD

**Issue by wsjq5477** [sjtuross/syno-iptables#27]
如题，新版本kernel变了，之前的ko插不进去了，想尝试重新编译，但spksrc的源码也没7.2的

**Comment by sjtuross** [comment]
kernel源码更新要等群晖发布，一般都比较滞后

你先贴一下`uname -a`和`iptables -V`的输出

**Comment by wsjq5477** [comment]
![image](https://github.com/sjtuross/syno-iptables/assets/34412208/40a85899-f72a-4c91-af76-2db8abff8c4c)
![image](https://github.com/sjtuross/syno-iptables/assets/34412208/083e6442-3c04-4cc3-9edf-c1c7fb4d14a9)
kernel升级到4.4.302了，问了群晖官方的人，貌似7.1以后的源码不会再开放了，还有啥可行的办法吗

**Comment by sjtuross** [comment]
你没理解对方的意思，SynoCommunity/spksrc本身不是群晖官方，它是spk安装包的交叉编译套件，人家告诉你群晖暂时还没把源码放出来。群晖对开源的Linux内核改动部分，是有义务开放出来的，人家给出的链接也是群晖官方的出处，但是群晖总是拖很久。

7.0到7.1内核版本没有升级，所以有没有新的源码对编译本模块来说无所谓。理论上可以用对应版本的linux kernel源码来尝试编译模块，但是还缺群晖的内核编译配置文件，难度应该不小，否则我相信SynoCommunity/spksrc早就有替代方案了，所以只能等了

**Comment by wsjq5477** [comment]
好吧我还以为spsrc是他们官方的人提供的，看来还有机会只能慢慢等了

**Comment by tokyoqiang** [comment]
今天升级完DSM7.2，我也遇到了同样问题，希望大佬能尽快解决，感谢！

https://github.com/v2rayA/v2rayA/issues/1103

![image](https://github.com/sjtuross/syno-iptables/assets/99979431/3d0931fb-b0f7-4de9-8287-a440fddf1103)

**Comment by YoungxuJi** [comment]
现在7.2版本的源码出来吗？ 有编译好的4.4.302+了吗？

**Comment by sjtuross** [comment]
最近群晖貌似把7.2的内核源码放出来了，[Synology NAS GPL Source](https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source)，但是上游spksrc编译框架还未整合，不过应该快了。

另外，这个项目[wjz304/syno-iptables](https://github.com/wjz304/syno-iptables)基于[SynologyOpenSource/pkgscripts-ng](https://github.com/SynologyOpenSource/pkgscripts-ng)也编译了相关模块。我把4.4.302常用的模块整合到本项目中了，但我自己暂时没有环境测试，你们可以试一下并反馈一下结果。

**Comment by YoungxuJi** [comment]
> 最近群晖貌似把7.2的内核源码放出来了，[Synology NAS GPL Source](https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source)，但是上游spksrc编译框架还未整合，不过应该快了。
> 
> 另外，这个项目[wjz304/syno-iptables](https://github.com/wjz304/syno-iptables)基于[SynologyOpenSource/pkgscripts-ng](https://github.com/SynologyOpenSource/pkgscripts-ng)也编译了相关模块。我把4.4.302常用的模块整合到本项目中了，但我自己暂时没有环境测试，你们可以试一下并反馈一下结果。

群晖DS220+ ，geminilake/kernel-4.4.302 模块经过测试没有报错，目前正常可用。

**Comment by tokyoqiang** [comment]
> > 最近群晖貌似把7.2的内核源码放出来了，[Synology NAS GPL Source](https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source)，但是上游spksrc编译框架还未整合，不过应该快了。
> > 另外，这个项目[wjz304/syno-iptables](https://github.com/wjz304/syno-iptables)基于[SynologyOpenSource/pkgscripts-ng](https://github.com/SynologyOpenSource/pkgscripts-ng)也编译了相关模块。我把4.4.302常用的模块整合到本项目中了，但我自己暂时没有环境测试，你们可以试一下并反馈一下结果。
> 
> 群晖DS220+ ，geminilake/kernel-4.4.302 模块经过测试没有报错，目前正常可用。

我的也没问题，感谢大佬！

**Comment by eks1024** [comment]
跪求7.2.1版本可用的ko模块和so模块，DS918+

DS918+的架构为apollolake
DS918+ DSM 7.2.1-69057 Update 1系统内核为4.4.302+

找遍了全网都找不到解决的方案

**Comment by serikaron** [comment]
> > 最近群晖貌似把7.2的内核源码放出来了，[Synology NAS GPL Source](https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source)，但是上游spksrc编译框架还未整合，不过应该快了。
> > 另外，这个项目[wjz304/syno-iptables](https://github.com/wjz304/syno-iptables)基于[SynologyOpenSource/pkgscripts-ng](https://github.com/SynologyOpenSource/pkgscripts-ng)也编译了相关模块。我把4.4.302常用的模块整合到本项目中了，但我自己暂时没有环境测试，你们可以试一下并反馈一下结果。
> 
> 群晖DS220+ ，geminilake/kernel-4.4.302 模块经过测试没有报错，目前正常可用。

~~你好，我也是群晖DS220+，更新了geminilake/kernel-4.4.302 模块之后，v2raya还不能用。请问有相关经验或者排查错误的方法分享吗，谢谢~~

谢谢楼下的回复，查了日志，翻了隔壁v2raya的issues，找到个类似的情况，解决了。

**Comment by YoungxuJi** [comment]
> > > 最近群晖貌似把7.2的内核源码放出来了，[Synology NAS GPL Source](https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source)，但是上游spksrc编译框架还未整合，不过应该快了。
> > > 另外，这个项目[wjz304/syno-iptables](https://github.com/wjz304/syno-iptables)基于[SynologyOpenSource/pkgscripts-ng](https://github.com/SynologyOpenSource/pkgscripts-ng)也编译了相关模块。我把4.4.302常用的模块整合到本项目中了，但我自己暂时没有环境测试，你们可以试一下并反馈一下结果。
> > 
> > 
> > 群晖DS220+ ，geminilake/kernel-4.4.302 模块经过测试没有报错，目前正常可用。
> 
> 你好，我也是群晖DS220+，更新了geminilake/kernel-4.4.302 模块之后，v2raya还不能用。请问有相关经验或者排查错误的方法分享吗，谢谢

报错信息先截图或打印贴出来看看

**Comment by sjtuross** [comment]
#28
