### ISSUE TITLE
增加了模块，在脚本里也insmod了，iptable仍报错

### ISSUE THREAD

**Issue by xushaobo** [sjtuross/syno-iptables#31]
iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument : exit status 4

环境：DS918+
           $uname -a: Linux DS918 4.4.180+ #42962 SMP Mon May 29 14:38:23 CST 2023 x86_64 GNU/Linux synology_apollolake_918+
           $iptables -V :iptables v1.8.3 (legacy): (报错是v1.8.10?)

**Comment by sjtuross** [comment]
我不知道你跑了什么应用或docker，docker中封装的iptables可能版本高，但只要调用的功能宿主系统支持就没问题，否则就会出错

如果你是用最新版v2rayA的话，试试添加下面2个环境变量，具体去看那边的说明

```
IPTABLES_MODE=legacy
V2RAYA_NFTABLES_SUPPORT=off
```

**Comment by xushaobo** [comment]
> 我不知道你跑了什么应用或docker，docker中封装的iptables可能版本高，但只要调用的功能宿主系统支持就没问题，否则就会出错
> 
> 如果你是用最新版v2rayA的话，试试添加下面2个环境变量，具体去看那边的说明
> 
> ```
> IPTABLES_MODE=legacy
> V2RAYA_NFTABLES_SUPPORT=off
> ```

你好请问一下DSM7.1版本的用了DSM7.0版本的文件会有影响吗，如果会影响，是要重新编译一下7.1所需的文件么

**Comment by sjtuross** [comment]
通过uname确定内核版本号来选择文件，不跟dsm版本直接相关

**Comment by xushaobo** [comment]
uname -a 输入前面帖了： Linux DS918 4.4.180+ #42962 SMP Mon May 29 14:38:23 CST 2023 x86_64 GNU/Linux synology_apollolake_918+

文件选的这个：https://github.com/sjtuross/syno-iptables/tree/master/apollolake/kernel-4.4.180

应该没错的吧

**Comment by sjtuross** [comment]
对的，没错

**Comment by xushaobo** [comment]
大佬能帮我看一下吗，卡在最后一步的感觉太难受
dmesg | tail查看加载失败的原因:

![image](https://github.com/sjtuross/syno-iptables/assets/13624577/3202ece6-b410-46a7-93a3-832e419c57fc)

**Comment by xushaobo** [comment]
Docker日志：（现在不加规则能启动）
加了报错：failed to start v2ray-core: not support "redirect" mode of transparent proxy: ExecCommands: iptables-legacy -w 2 -t nat -N TP_OUT iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument : exit status 4

![image](https://github.com/sjtuross/syno-iptables/assets/13624577/a31ad190-391d-4190-95de-711bbab2816a)

**Comment by sjtuross** [comment]
至今你都没说你跑的哪个docker，怎么帮你？你要说这是v2ray，那包含v2ray-core的docker多了去了。把怎么跑docker的完整信息贴出来看看

**Comment by xushaobo** [comment]
docker 运行的是这个,还需要安装另外的v2ray-core的容器吗

docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya \
  -e V2RAYA_ADDRESS=0.0.0.0:2017 \
  -v /lib/modules:/lib/modules \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /volume1/docker/v2raya-config:/etc/v2raya \
  --entrypoint /etc/v2raya/bootstrap.sh \
  mzz2017/v2raya

**Comment by xushaobo** [comment]
可以了可以了,谢谢大佬
添加这两个就好
IPTABLES_MODE=legacy
V2RAYA_NFTABLES_SUPPORT=off
