### ISSUE TITLE
希望增加群晖923+

### ISSUE THREAD

**Issue by binhe-cpu** [sjtuross/syno-iptables#32]
![image](https://github.com/sjtuross/syno-iptables/assets/61576528/81cb9505-5e7a-4f24-8552-45b840d29bd3)

**Comment by binhe-cpu** [comment]
![image](https://github.com/sjtuross/syno-iptables/assets/61576528/9fed8805-7bb8-47c5-978f-1a82d9dc3f88)

**Comment by sjtuross** [comment]
之前编译过的，放上来了，你试试看吧

https://github.com/sjtuross/syno-iptables/tree/master/r1000/kernel-4.4.302

**Comment by binhe-cpu** [comment]
谢谢，可以使用了！不过用通用模块加载保存文件出错
![image](https://github.com/sjtuross/syno-iptables/assets/61576528/b9017a24-527c-4c16-a3b8-fac64ecaefe8)

**Comment by sjtuross** [comment]
这个要root用户编辑才有权限保存的，比如`sudo -i`之后用vim，或者想其他办法

**Comment by binhe-cpu** [comment]
好的，谢谢！

sjtuross ***@***.***> 于 2024年4月16日周二 下午5:14写道：
