### ISSUE TITLE
【请教】DS918+添加这些iptables模块后passwall、SSR plus还是不能实现代理

### ISSUE THREAD

**Issue by hululu1068** [sjtuross/syno-iptables#7]
DS918+ 7.0.1-42218系统
通过Docker创建openwrt容器，本来想做旁路由的，添加了项目的iptables模块，遗憾的是Passwall、SSR+还是不能实现代理。
看到这个帖子 https://blog.zhaoweichen.cn/zh-hans/node/29
是否还需要添加ipset模块？
谢谢！

**Comment by hululu1068** [comment]
是否还需要dnsmasq模块的支持？

**Comment by sjtuross** [comment]
缺的ipset模块`ip_set_hash_net.ko`已经提供了，暂时没发现需要额外的模块

我测试过了没问题，记录了一下过程，供你参考：[Docker安装OpenWrt旁路由](https://github.com/sjtuross/syno-iptables/wiki/Docker安装OpenWrt旁路由)

**Comment by sjtuross** [comment]
另外需要补一个`xt_comment.ko`，加进去了https://github.com/sjtuross/syno-iptables/tree/master/apollolake/kernel-4.4.180/ko

**Comment by hululu1068** [comment]
> 另外需要补一个`xt_comment.ko`，加进去了https://github.com/sjtuross/syno-iptables/tree/master/apollolake/kernel-4.4.180/ko

谢谢！现在就试试

**Comment by sjtuross** [comment]
配套的`libxt_comment.so`也补了，另外Wiki更新了一下docker run，挂载了/lib/modules，可能有用

如果还有问题，运行`/etc/init.d/shadowsocksr restart`，把错误信息贴出来，正常启动是没有任何输出的

**Comment by hululu1068** [comment]
> 配套的`libxt_comment.so`也补了，另外Wiki更新了一下docker run，挂载了/lib/modules，可能有用
> 
> 如果还有问题，运行`/etc/init.d/shadowsocksr restart`，把错误信息贴出来，正常启动是没有任何输出的


非常感谢！不用挂载/lib/modules也可以

SSR+可以完美运行
Passwall 选择REDIRECT 重定向模式可以代理，TPROXY 透明代理模式不行，缺‘socket’文件
![image](https://user-images.githubusercontent.com/68652362/160156951-e834a60a-27ad-4073-a67e-3967508a7f48.png)

从测速来看，似乎比在虚拟机下慢了不少，只有1/3

另外，我用的官方源码编译的，插件也是目前最新的
https://hub.docker.com/repository/docker/xjianglin/openwrt


PS：我整理了一份虚拟机里openwrt的‘modules’和‘iptables’清单，希望判断时有帮助
[Openwrt-21.02.2_lib-modules-5.4.179.xlsx](https://github.com/sjtuross/syno-iptables/files/8352279/Openwrt-21.02.2_lib-modules-5.4.179.xlsx)

**Comment by sjtuross** [comment]
@hululu1068 感谢反馈！

发现之前编译的ko模块默认带debug信息，导致模块文件都很大，我重新编译上传了apollolake kernel-4.4.180的所有ko模块，把debug信息都去掉了，现在体积很小了，可能对性能有帮助。

另外`xt_socket.ko`也提供了，passwall TPROXY模式可以正常使用，但必须禁用LAN接口桥接才行，Wiki更新了。

试试吧，https://github.com/sjtuross/syno-iptables/tree/master/apollolake/kernel-4.4.180/ko

**Comment by hululu1068** [comment]
> @hululu1068 感谢反馈！
> 
> 发现之前编译的ko模块默认带debug信息，导致模块文件都很大，我重新编译上传了apollolake kernel-4.4.180的所有ko模块，把debug信息都去掉了，现在体积很小了，可能对性能有帮助。
> 
> 另外`xt_socket.ko`也提供了，passwall TPROXY模式可以正常使用，但必须禁用LAN接口桥接才行，Wiki更新了。
> 
> 试试吧，https://github.com/sjtuross/syno-iptables/tree/master/apollolake/kernel-4.4.180/ko

试了下，基本完美了，速度也正常了。。。。牛逼@sjtuross
关于添加的模块重启后不自动加载的情况，发现通过添加群晖系统自带的计划任务可以实现
再次感谢！
