### ISSUE TITLE
自行编译到最后一步报错

### ISSUE THREAD

**Issue by 412999826** [sjtuross/syno-iptables#8]
make[1]: Entering directory '/spksrc/kernel/syno-rtd1296-7.0/work/linux'
make[2]: *** Documentation/Kbuild: Is a directory.  Stop.
make[1]: *** [Makefile:1249: _clean_Documentation] Error 2
make[1]: Leaving directory '/spksrc/kernel/syno-rtd1296-7.0/work/linux'
make: *** [../../mk/spksrc.kernel.mk:96: kernel_configure_target] Error 2

想对arm的群晖编译，但是第一步的最后就报错了，不知道怎么解决？
如果方便的话可否帮忙编译一份syno-rtd1296-7.0？

**Comment by sjtuross** [comment]
试试吧，[rtd1296/kernel-4.4.180](https://github.com/sjtuross/syno-iptables/tree/master/rtd1296/kernel-4.4.180)

**Comment by 412999826** [comment]
> 试试吧，[rtd1296/kernel-4.4.180](https://github.com/sjtuross/syno-iptables/tree/master/rtd1296/kernel-4.4.180)

好的，我试试，感谢

**Comment by sjtuross** [comment]
编译文档也更新了一下，适配arm64 a83d89ad8aea33fe9260d4e3a17ca32852ea45fe

**Comment by 412999826** [comment]
> 编译文档也更新了一下，适配arm64 [a83d89a](https://github.com/sjtuross/syno-iptables/commit/a83d89ad8aea33fe9260d4e3a17ca32852ea45fe)
使用您编译的，发现加载这个模块报错，是啥问题啊？
insmod: ERROR: could not insert module /lib/modules/xt_TPROXY.ko: Unknown symbol in module

**Comment by sjtuross** [comment]
这个错一般是指缺少依赖。你是按照次序加载的吗？有些是系统自带的，但必须按依赖次序加载

另外，运行`dmesg | tail`看下具体信息

**Comment by 412999826** [comment]
> 这个错一般是指缺少依赖。你是按照次序加载的吗？有些是系统自带的，但必须按依赖次序加载
> 
> 另外，运行`dmesg | tail`看下具体信息

是依次加载，前面的加载都通过了，
root@DS118:~# insmod /lib/modules/nfnetlink.ko
root@DS118:~# insmod /lib/modules/ip_set.ko
root@DS118:~# insmod /lib/modules/ip_set_hash_ip.ko
root@DS118:~# insmod /lib/modules/xt_set.ko
root@DS118:~# insmod /lib/modules/ip_set_hash_net.ko
root@DS118:~# insmod /lib/modules/xt_mark.ko
root@DS118:~# insmod /lib/modules/xt_connmark.ko
root@DS118:~# insmod /lib/modules/xt_comment.ko
root@DS118:~# insmod /lib/modules/xt_TPROXY.ko
insmod: ERROR: could not insert module /lib/modules/xt_TPROXY.ko: Unknown symbol in module


dmesg | tail具体信息如下：

[129216.326202] Module [xt_iprange] is removed. 
[129216.386253] Module [xt_limit] is removed. 
[129216.436039] Module [xt_state] is removed. 
[129216.510755] Module [xt_multiport] is removed. 
[129216.566106] Module [xt_LOG] is removed. 
[129216.625807] Module [iptable_filter] is removed. 
[129224.137154] audit: type=1325 audit(1650346361.899:195): table=filter family=2 entries=0
[129278.092810] Netfilter messages via NETLINK v0.30.
[129278.108995] ip_set: protocol 6
[129290.756797] xt_TPROXY: Unknown symbol nf_defrag_ipv6_enable (err 0)

**Comment by 412999826** [comment]
> 这个错一般是指缺少依赖。你是按照次序加载的吗？有些是系统自带的，但必须按依赖次序加载
> 
> 另外，运行`dmesg | tail`看下具体信息

另外，还有三个文件我的系统没有，不知道是不是这个有影响，textsearch.ko、ts_bm.ko、xt_string.ko

root@DS118:~# insmod /lib/modules/xt_socket.ko
insmod: ERROR: could not insert module /lib/modules/xt_socket.ko: Unknown symbol in module
root@DS118:~# insmod /lib/modules/iptable_mangle.ko
root@DS118:~# insmod /lib/modules/textsearch.ko
insmod: ERROR: could not load module /lib/modules/textsearch.ko: No such file or directory
root@DS118:~# insmod /lib/modules/ts_bm.ko
insmod: ERROR: could not load module /lib/modules/ts_bm.ko: No such file or directory
root@DS118:~# insmod /lib/modules/xt_string.ko
insmod: ERROR: could not load module /lib/modules/xt_string.ko: No such file or directory

**Comment by sjtuross** [comment]
`xt_string.ko`等3个模块是最近加进去的，下载最新版 https://github.com/sjtuross/syno-iptables/releases

`[129290.756797] xt_TPROXY: Unknown symbol nf_defrag_ipv6_enable (err 0)`

根据这行出错信息，试试看先加载这个系统自带模块`nf_defrag_ipv6.ko`

```
insmod /lib/modules/nf_defrag_ipv6.ko
insmod /lib/modules/xt_TPROXY.ko
```

**Comment by 412999826** [comment]
> 

可以了，非常感谢！！！！
